In [4]:
import numpy as np

In [5]:
x=np.array([1,2,3,4,5])

In [6]:
print(x)

[1 2 3 4 5]


In [7]:
y=np.array([[1,2],[2,3],[3,4]])
print(y)

[[1 2]
 [2 3]
 [3 4]]


In [8]:
print("Element (0,0)",y[0,0])
print("Element (1,0)",y[1,0])
print("Element (2,0)",y[2,0])

Element (0,0) 1
Element (1,0) 2
Element (2,0) 3


In [9]:
y[0,1]=20
print(y)

[[ 1 20]
 [ 2  3]
 [ 3  4]]


In [10]:
"""
DELETE FUNCTION IN NUMPY
np.delete(ndarray,elements,axis)
axis=0 #refer to x axis -- row
axis=1 #refer to y axis -- column
"""

tempONE=np.arange(1,6)
print("before delete:",tempONE)
np.delete(tempONE,3)
print(tempONE)
tempTWO=np.arange(1,10).reshape(3,3)
print("before delete:\n",tempTWO)
W=np.delete(tempTWO,0,axis=0)
print("after delete:\n",W)
Z=np.delete(tempTWO,[0,2],axis=1)
print("after delete:\n",Z)


before delete: [1 2 3 4 5]
[1 2 3 4 5]
before delete:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
after delete:
 [[4 5 6]
 [7 8 9]]
after delete:
 [[2]
 [5]
 [8]]


In [11]:
"""
DELETE FUNCTION IN NUMPY
np.append(ndarray,elements,axis)
axis=0 #refer to x axis -- row
axis=1 #refer to y axis -- column
"""

'\nDELETE FUNCTION IN NUMPY\nnp.append(ndarray,elements,axis)\naxis=0 #refer to x axis -- row\naxis=1 #refer to y axis -- column\n'

In [12]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 3, 4, 5])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])

# We print x
print()
print('Original x = ', x)

# We append the integer 6 to x
x = np.append(x, 6)

# We print x
print()
print('x = ', x)

# We append the integer 7 and 8 to x
x = np.append(x, [7,8])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We append a new row containing 7,8,9 to y
v = np.append(Y, [[7,8,9]], axis=0)

# We append a new column containing 9 and 10 to y
q = np.append(Y,[[9],[10]], axis=1)

print(v)
print(q)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]

Original Y = 
 [[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  9]
 [ 4  5  6 10]]


In [15]:
# We create a rank 1 ndarray 
x = np.array([1, 2, 5, 6, 7])

# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])

# We print x
print()
print('Original x = ', x)

# We insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])

# We print x with the inserted elements
print()
print('x = ', x)

# We print Y
print()
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,[5,6], axis=1)

# We print w
print()
print('w = \n', w)

# We print v
print()
print('v = \n', v)


Original x =  [1 2 5 6 7]

x =  [1 2 3 4 5 6 7]

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 6 8 9]]


In [19]:
# We create a rank 1 ndarray 
x = np.array([1,2])

# We create a rank 2 ndarray 
Y = np.array([[3,4],[5,6]])

# We print x
print()
print('x = ', x)

# We print Y
print()
print('Y = \n', Y)

# We stack x on top of Y
z = np.vstack((x,Y))

# We stack x on the right of Y. We need to reshape x in order to stack it on the right of Y. 
w = np.hstack((Y,x.reshape(2,1)))

# print(x.reshape(2,1))
# We print z
print()
print('z = \n', z)

# We print w
print()
print('w = \n', w)


x =  [1 2]

Y = 
 [[3 4]
 [5 6]]

z = 
 [[1 2]
 [3 4]
 [5 6]]

w = 
 [[3 4 1]
 [5 6 2]]
